# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build in REST example
      run: cd rest; go build main.go

    - name: run test in REST example
      run: cd rest; go test -v ./...

    - name: Build CLI
      run: cd cli; go build .

    - name: Build Linked list example
      run: cd linked-list; go build .


